### ISSUE TITLE
Gem installation reports dependency failure

### ISSUE THREAD

**Issue by phene** [brendon/canonix#8]
```
$ gem install canonix
Fetching: canonix-0.1.7.gem (100%)
ERROR:  Error installing canonix:
    canonix requires canonix (>= 0)
```

**Comment by brendon** [comment]
Hi Phene, I'm not sure what's causing this. But more to the point, I don't think canonix is required anymore because there are better alternatives. ruby-saml has moved away to another project and I'm not sure anything else is using this gem. Let me know if you still require it fixed up and I'll take another look  :)

**Comment by phene** [comment]
Gems shouldn't be dependencies of themselves: https://github.com/brendon/canonix/blob/master/canonix.gemspec#L50

**Comment by brendon** [comment]
Yes, it seems that Jeweler is generating this. I've had a go at fixing it
but can't seem to figure out why it's including itself as a dependency. If
you have any ideas they'd be more than welcome :)

**Comment by Piyushchoudhary** [comment]
Any updates on this issue. I am facing the same issue.

**Comment by phene** [comment]
The gem has been marked as obsolete. Abandon all hope, ye who enter here.

**Comment by brendon** [comment]
Hehe, it's not actually used anywhere that I'm aware of now. The only
dependency that existed was with various version of ruby-saml. The latest
version of ruby-saml doesn't have the dependency, so updating to that
version should fix your dependency problem.

Farewell poorly written gem!

Brendon Muir

On Wed, Apr 22, 2015 at 4:42 AM, Geoffrey Hichborn <notifications@github.com

**Comment by bournsh** [comment]
I am not sure , even after a successful update of bundle, why I'm getting certain gems under `$gem outdated`

**Comment by brendon** [comment]
Sorry, I'm not sure I can help. This gem is obsolete now.
